### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by hfiguiere** [flathub/com.arteeh.Flasher#1]
The latest build failed because the appstream file tries to get screenshot from a gitlab repository that is either gone or not public.

https://gitlab.com/arteeh/pinetime-flasher/-/raw/master/data/screenshot1.png
https://gitlab.com/arteeh/pinetime-flasher/-/raw/master/data/screenshot2.png

**Comment by arteeh** [comment]
Fixed with #5
