### ISSUE TITLE
Icon and name has official Pine64 brandings

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.arteeh.Flasher#3]
Hello we are tracking a bunch of applications with trademark violations

The current name and icon carries brandings from official Pine64 products https://pine64.org/devices/pinetime/ but this is an unofficial client.

Please try to use your own name and icon for the application to avoid trademark issues and confusing people. I think 2 months is a reasonable time period for us to wait for the icon to be changed.

You can find some resources for icon guidelines in https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#app-icon and name in https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#app-name

And the guidelines on trademarks https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#no-trademark-violations

**Comment by bbhtt** [comment]
@arteeh any update? Is this EOL? Then you should mark it as such https://docs.flathub.org/docs/for-app-authors/maintenance#end-of-life

**Comment by arteeh** [comment]
Lukasz Erecinski gave me permission to use the icon in this app. He was community manager of PINE64 at the time.

But yes, this app is unmaintained and practically useless. I'll add the EOL marker.
